services:
  webserver:
    build: .
    image: mfandrade/stackio-webserver:latest
    ports:
      - 8080:8080
    volumes:
      - ./database.pw:/var/tmp/database.pw
    depends_on:
      - backend
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080",
        ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

  backend:
    image: mariadb:11
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=db
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD_FILE=/run/secrets/mariadb_password
    secrets:
      - mariadb_password
    ports:
      - 3306:3306
    volumes:
      - mariadb_volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "-f", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

secrets:
  mariadb_password:
    file: ./database.pw

volumes:
  mariadb_volume:
