services:

  webserver:
    build: .
    image: mfandrade/stackio:latest
    ports:
      - 8080:8080
    volumes:
      - ./database.pw:/var/tmp/database.pw
    depends_on:
      - backend

  backend:
    image: mariadb:11
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=db
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD_FILE=/run/secrets/mariadb_password
    secrets:
      - mariadb_password
    ports:
      - 3306:3306
    volumes:
      - mariadb_volume:/var/lb/mysql

secrets:
  mariadb_password:
    file: ./database.pw

volumes:
  mariadb_volume:
