kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: stackio
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - image: mfandrade/stackio-webserver:latest
          name: stackio-webserver
          ports:
            - containerPort: 8080
