kind: Namespace
apiVersion: v1
metadata:
  name: stackio

---
kind: Secret
apiVersion: v1
metadata:
  namespace: stackio
  name: mariadb-password
type: Opaque
data:
  database.pw: UEA1NXdyMHJkIQo=

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: stackio
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - image: mfandrade/stackio-webserver:latest
          imagePullPolicy: Always
          name: stackio-webserver
          volumeMounts:
            - name: secret-volume
              mountPath: /run/secrets/mariadb-password
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 30
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            initialDelaySeconds: 3
            periodSeconds: 5
            httpGet:
              path: /
              port: 8080
      volumes:
        - name: secret-volume
          secret:
            secretName: mariadb-password

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: stackio
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: mfandrade/stackio-backend:latest
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 3306

          livenessProbe:
            exec:
              command:
                - mysqladmin
                - "-f"
                - "localhost"
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            exec:
              command:
                - mysqladmin
                - "-f"
                - "localhost"
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3

      volumes:
        - name: mariadb-password-volume
          secret:
            secretName: mariadb-password # Ensure this matches your created secret name

