kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: stackio
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - image: mfandrade/stackio-webserver:latest
          name: stackio-webserver
          volumeMounts:
            - name: secret-volume
              mountPath: /run/secrets/mariadb_password
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 30
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            initialDelaySeconds: 3
            periodSeconds: 5
            httpGet:
              path: /
              port: 8080
      volumes:
        - name: secret-volume
          secret:
            secretName: mariadb_password

---
kind:
apiVersion: v1
metadata:
  name: mariadb_password
  namespace: default
type: Opaque
data:
  database.pw: UEA1NXdyMHJkIQo=
