apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
  namespace: stackio
  creationTimestamp: null
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      namespace: stackio
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
        - image: mfandrade/stackio-backend:latest
          imagePullPolicy: Always
          name: stackio-backend
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - name: credentials-volume
              mountPath: /mnt/credentials-volume
              readOnly: true
          env:
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: MARIADB_PASSWORD
      volumes:
        - name: credentials-volume
          secret:
            secretName: credentials
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: backend-srv
  namespace: stackio
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 3306
      protocol: TCP
