---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackio-webserver
  namespace: stackio
  creationTimestamp: null
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  strategy: {}
  template:
    metadata:
      namespace: stackio
      creationTimestamp: null
      labels:
        app: webserver
    spec:
      containers:
        - image: mfandrade/stackio-webserver:latest
          name: webserver
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: MARIADB_PASSWORD
          volumeMounts:
            - name: credentials-volume
              mountPath: /mnt/credentials-volume
              readOnly: true
      volumes:
        - name: credentials-volume
          secret:
            secretName: credentials
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webserver
  name: webserver
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: webserver
  type: LoadBalancer
status:
  loadBalancer: {}
